### ISSUE TITLE
pyfont not included

### ISSUE THREAD

**Issue by coylen** [peterhinch/micropython-epaper#4]
Hi, 
Excellent work I love this driver, however I have a bit of a problem with the latest version.  The readme implies that a new module 'pyfont.py' should exist and indeed the driver fails on import of this module in the epaper.py file.  I am not sure if this is just missing from the repository or if pyfont is a python standard library that I need to obtain from elsewhere.

**Comment by peterhinch** [comment]
Apologies, now included. I've been doing some development of this driver to support a real time mode, you might like to give it a try. The README explains it, but it is at a somewhat beta stage.

**Comment by coylen** [comment]
Thanks, the FAST mode looks ideal for my use, I will give it a try this evening and report back any issues.  Will FAST mode benefit from frozen fonts, or will fonts on my pyboard SD card be sufficient from a speed point of view?

**Comment by peterhinch** [comment]
Good question. FAST mode is very much under development and I haven't had a chance to benchmark this. The issue with fonts is RAM consumption: the driver is fairly RAM heavy and there's no way the normal approach of loading a font into RAM would work. To access a character on a font on disk random file access is used with only a single character being in RAM at any one time. This is inevitably slower than accessing a frozen bytearray.

However rendering a text string to the driver's buffer takes place when the font's context manager is run. Displaying the result occurs when show() or refresh() is called. So font rendering time has no effect on the display update speed. Its effect on the application as a whole rather depends on the nature of the application. You may want to develop with fonts on disk then migrate them - persistent bytecode is not yet supported on the main MicroPython branch and you'll need to grab PR #1811 if you want to try it.

FAST mode does suffer from a degree of ghosting. I've gone to some lengths to reduce it, including use of assembler, but I've failed so far to eliminate it. I've seen videos on the web of these displays being updated very fast without ghosting, but no code is on offer. Mine is based on the RePaper reference code, and such rapid updates would be impossible with their design because of explicit time delays. There may be reasons to avoid methods not based on the reference design as I've seen references to premature wear on the display particles if the display is "overdriven" - whatever that means.

I'd be interested to hear your experiences and opinions.
